// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ZvZsIq0QvUNFjXqKqPsYUDb0SZ5PqlY',
    appId: '1:443526782067:web:d3991b0df971e699f1de06',
    messagingSenderId: '443526782067',
    projectId: 'oja-ewa',
    authDomain: 'oja-ewa.firebaseapp.com',
    storageBucket: 'oja-ewa.firebasestorage.app',
    measurementId: 'G-X9XKB4K3EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5uqYT7YgfcaTFhuRcHQX7rvw5SGSowkU',
    appId: '1:443526782067:android:fb0fcfd661b49cb6f1de06',
    messagingSenderId: '443526782067',
    projectId: 'oja-ewa',
    storageBucket: 'oja-ewa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFpvVz_tmQZKYzW8_muFkNxn7hvnzfGCA',
    appId: '1:443526782067:ios:afc0bbad11313ca8f1de06',
    messagingSenderId: '443526782067',
    projectId: 'oja-ewa',
    storageBucket: 'oja-ewa.firebasestorage.app',
    androidClientId: '443526782067-v1t744oikqspg3ghs98a4mulmkop36k1.apps.googleusercontent.com',
    iosClientId: '443526782067-ga3m3iqcgh47cgflsq4us1736sv01hda.apps.googleusercontent.com',
    iosBundleId: 'com.wawuafrica.ojaewa',
  );
}
