import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app/app.dart';
import 'core/auth/auth_controller.dart';
import 'core/notifications/fcm_service.dart';
import 'features/notifications/data/notifications_repository_impl.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase with platform-specific options
  // Generated by `flutterfire configure`
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Ensure auth token is loaded before any network calls.
  final container = ProviderContainer();
  await container.read(authControllerProvider.notifier).loadFromStorage();

  // Initialize FCM for push notifications (after container is ready)
  final notificationsApi = container.read(notificationsApiProvider);
  FCMService(notificationsApi: notificationsApi);

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const App(),
    ),
  );
}
